### ISSUE TITLE
unlimited results!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [patelharsh80874/THE-ULTIMATE-SONGS-WEBAPP#1]
woow amazing project dude.but please could you make it increase unlimited results?it would be great!!!

**Comment by patelharsh80874** [comment]
unlimited results in which part/section ?

**Comment by KENPOKASMMA1982** [comment]
> unlimited results in which part/section ?

my friend unlimited results for songs and albums!!!pleaseeeeeeeeeeeeeeeeee!!!!

**Comment by patelharsh80874** [comment]
### **_UPDATE_**

**unlimited results are not possible because it will increase load on website and decrease website performance, but i just updated and Increased results by 2X**

### **home page** : Increased home page song's results to **350+ songs upto 25 pages**, with interval of 2 seconds
### **note : sometime songs are repeated because its generate page number using math.random()**


### **song and album search page :** Song and album search page results **increased by 220+ upto 20 pages** , with interval of 2 seconds

**Comment by KENPOKASMMA1982** [comment]
my friend thanks a lot but could you remove all the duplicate songs and with some way increase unlimited results?I AM BEGGING YOU!!!

**Comment by patelharsh80874** [comment]
I will try to implement **infinite-scroll** , it will call new data based on scrolling .

**Comment by KENPOKASMMA1982** [comment]
> I will try to implement **infinite-scroll** , it will call new data based on scrolling .

Woowwwwwwwwww thanks so much!!!!!!!!!!!!!!!!and please could you remove all the duplicate files...It would be great!!!

**Comment by patelharsh80874** [comment]
**### UPDATE** 

1. **HOME page** : home page songs repeating/duplicate  issue fixed 
 
2. **infinite-scroll** : added infinite-scroll in songs and album search page it will call new data based on scrolling.

**Comment by KENPOKASMMA1982** [comment]
> **### UPDATE**
> 
> 1. **HOME page** : home page songs repeating/duplicate  issue fixed
> 2. **infinite-scroll** : added infinite-scroll in songs and album search page it will call new data based on scrolling.

my friend thanks so muchhhhhhhhhhhh but infinite scroll not working....says loading but not working for more results!!!

**Comment by patelharsh80874** [comment]
New data was doesn't load Because its doesn't have new data , its end of the results , i was forgot to update text message on end of all results . i will fix that

**Comment by KENPOKASMMA1982** [comment]
> New data was doesn't load Because its doesn't have new data , its end of the results , i was forgot to update text message on end of all results . i will fix that

my friend thanks so much but it must increase unlimited results....your amazing project shows just few!!!

**Comment by patelharsh80874** [comment]
UPDATE 

loading... bug fixed

when you search hindi keyword , jiosaavan repeats songs after 1010 results, and our website also shows 1010 results, jiosaavan repeats songs after 1010 results but our website doesn't repeat songs that means you are at the end of results.  i attached the Screenshot and Screen Recording.

https://github.com/patelharsh80874/THE-ULTIMATE-SONGS-WEBAPP/assets/110234600/ee5f51d0-337c-46b7-a4cb-c36375ad66c8

![Screenshot 2024-04-14 172647](https://github.com/patelharsh80874/THE-ULTIMATE-SONGS-WEBAPP/assets/110234600/ab6bfee3-09ab-4a8a-8e33-36551823309b)

**Comment by KENPOKASMMA1982** [comment]
> UPDATE
> 
> loading... bug fixed
> 
> when you search hindi keyword , jiosaavan repeats songs after 1010 results, and our website also shows 1010 results, jiosaavan repeats songs after 1010 results but our website doesn't repeat songs that means you are at the end of results. i attached the Screenshot and Screen Recording.
> 
>  Recording.jiosaavan.mp4 
> ![Screenshot 2024-04-14 172647](https://private-user-images.githubusercontent.com/110234600/322272309-ab6bfee3-09ab-4a8a-8e33-36551823309b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTg1MTUsIm5iZiI6MTcxMzA5ODIxNSwicGF0aCI6Ii8xMTAyMzQ2MDAvMzIyMjcyMzA5LWFiNmJmZWUzLTA5YWItNGE4YS04ZTMzLTM2NTUxODIzMzA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWIzMGVlYmIyNzlkZmI3NmY5NzU3N2FjNTQzN2IwYWQ3NjgyNGMzMWFiNWZmYjFkYzFhMGE5N2I5MjhmNDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AEAAb9S8O9KXGBhGSigK1aiZZX-YrbrckEpc5GPDWiM)

my friend I have no words for your help but still not appear unlimited results...increase just so few....if you make one pagination orsomething like that?because infinite scroll shows just very few results!!!

**Comment by patelharsh80874** [comment]
**Website works fine and infinite scroll also works fine I checked on my 4 devices, showing as many results as available. You can go to jiosaavan  website and cross check with the same keywords that you have searched in the Ultimate Songs website.**

 _Are you satisfied with the solution to your issue? , if you are satisfied then suggest this project to others and like this project so that the project gets more popular, now I can close this issue ?_

**Comment by KENPOKASMMA1982** [comment]
> **Website works fine and infinite scroll also works fine I checked on my 4 devices, showing as many results as available. You can go to jiosaavan website and cross check with the same keywords that you have searched in the Ultimate Songs website.**
> 
> _Are you satisfied with the solution to your issue? , if you are satisfied then suggest this project to others and like this project so that the project gets more popular, now I can close this issue ?_

my friend look...I love spanish music and right now I check for the song dejame and increase just 285 songs...imagine it must increase at least 6000 results!!!I am sure about it!!!

**Comment by patelharsh80874** [comment]
I think this problem comes because API of this project is hosted on vercel platform, so there is problem in API response. Maybe Vercel may have response limiting . But I think search responses/results  are more than enough to explore famous songs

**Comment by KENPOKASMMA1982** [comment]
> Νομίζω ότι αυτό το πρόβλημα προκύπτει επειδή το API αυτού του έργου φιλοξενείται στην πλατφόρμα vercel, επομένως υπάρχει πρόβλημα στην απόκριση API. Ίσως η Vercel να έχει περιορισμό απόκρισης. Αλλά νομίζω ότι οι απαντήσεις/αποτελέσματα αναζήτησης είναι υπεραρκετές για να εξερευνήσετε διάσημα τραγούδια

I AM AFRAID WITH INFINITE SCROLL CANT WORK CORRECT!MAYBE WITH SOME PAGINATION!BUT BY THE WAY THANKS SO MUCH FOR EVERYTHING!!!

**Comment by patelharsh80874** [comment]
Pagination is required, each page in the API call returns 40 songs in response. _I close this issue now_

Thank you.

**Comment by KENPOKASMMA1982** [comment]
> Pagination is required, each page in the API call returns 40 songs in response. _I close this issue now_
> 
> Thank you.

OR WITH ONE BUTTON LOAD MORE MY FRIEND...MAYBE THIS WILL BE WORK BETTER!!!

**Comment by patelharsh80874** [comment]
This is already implemented. When you scroll to the end, the page value is incremented by +1 and returns new data.

**Comment by KENPOKASMMA1982** [comment]
> This is already implemented. When you scroll to the end, the page value is incremented by +1 and returns new data.

MY FRIEND REALLY I APRECIATE YOUR NEW UPDATES AND YOUR HELP....YOU HAVE CREATE ONE AMAZINGGGGGGGGGGG PROJECT...THE ONLY DISADVANTAGE IS THE FEW RESULTS!!!I HOPE YOU WILL MAKE IT INCREASE UNLIMITED RESULTS WITH SOME WAY!!!
