### ISSUE TITLE
RESULTS!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [patelharsh80874/THE-ULTIMATE-SONGS-WEBAPP#2]
MY FRIEND WHAT AMAZING PROJECT...REALLY MANY CONGRATULATIONS!!!LOOK I THINK JIOSAAVN INCREASE FEW RESULTS...CAN YOU TRY WITH SOME WAY LIKE PAGINATION OR WITH ONE BOTTON LOAD MORE INCREASE UNLIMITED???

**Comment by patelharsh80874** [comment]
**UPDATE**

**(Load more)** button has been added in the songs page. Click on the button to increment the value of the page. Even though infinite scroll has ended, clicking the button increments the page value and adds data, if data is received. 


**Note**:
_(load more)_ button is shown only when infinite scroll ends

**Comment by KENPOKASMMA1982** [comment]
> **UPDATE**
> 
> **(Load more)** button has been added in the songs page. Click on the button to increment the value of the page. Even though infinite scroll has ended, clicking the button increments the page value and adds data, if data is received.
> 
> **Note**: _(load more)_ button is shown only when infinite scroll ends

unfortunately tha same problem...load many duplicate songs!!!what a pitty!!!

**Comment by patelharsh80874** [comment]
~~Infinite scroll has ended, it means now there are no new songs in the next page, if repeated songs come from the next page, then the infinite scroll will end. But if you force call songs by clicking on load more button then whatever songs will come in response will be shown, it will not check whether that data is repeated or not.~~


**This issue now fixed**

**Comment by patelharsh80874** [comment]
**UPDATE** 

Load more fixed, now it removes duplicate songs and shows new songs, but shows new songs only if there are new songs in that page. And if new songs are not coming then click on load more button again and search for new songs in the next page and if new songs come then it will show new data.
